create table tb_medicos (
  id bigint not null auto_increment,
  nome varchar(100) not null,
  email varchar(100) not null,
  telefone varchar(20) not null,
  crm varchar(6) not null,
  especialidade varchar(100) not null,
  logradouro varchar(100) not null,
  bairro varchar(100) not null,
  cep varchar(9) not null,
  complemento varchar(100) null,
  numero varchar(20) null,
  uf varchar(2) not null,
  cidade varchar(100) not null,
  flativo tinyint not null,
  primary key (id),
  unique index email_unique (email asc) visible,
  unique index crm_unique (crm asc) visible);